local HttpService = game:GetService("HttpService")

local encoded = [[
CmxvY2FsIFBsYXllcnMgPSBnYW1lOkdldFNlcnZpY2UoIlBsYXllcnMiKQpsb2NhbCBUd2VlblNlcnZpY2UgPSBnYW1lOkdldFNlcnZpY2UoIlR3ZWVuU2VydmljZSIpCmxvY2FsIFJ1blNlcnZpY2UgPSBnYW1lOkdldFNlcnZpY2UoIlJ1blNlcnZpY2UiKQpsb2NhbCBscCA9IFBsYXllcnMuTG9jYWxQbGF5ZXIKbG9jYWwgY2hyID0gbHAuQ2hhcmFjdGVyIG9yIGxwLkNoYXJhY3RlckFkZGVkOldhaXQoKQpsb2NhbCBocnAgPSBjaHI6V2FpdEZvckNoaWxkKCJIdW1hbm9pZFJvb3RQYXJ0IikKbG9jYWwgaHVtID0gY2hyOldhaXRGb3JDaGlsZCgiSHVtYW5vaWQiKQoKLS0gQ8OgaSDEkeG6t3QKbG9jYWwgcmFkaXVzID0gMTAgLS0gYsOhbiBrw61uaCBjaOG6oXkg
]]

local scriptData = HttpService:Base64Decode(encoded)
loadstring(scriptData)()